insert into costume (name, size, genre, sex, borrowed_till) values ('Spiderman', 'XL', 'SUPERHEROES','MALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Capitan Marvel', 'S', 'SUPERHEROES','FEMALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Iron Man', 'M', 'SUPERHEROES','MALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Wilkolak', 'L', 'HORROR','REST', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Czarownica z Salem', 'M', 'HORROR','FEMALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Zombie', 'L', 'HORROR','MALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Bandyta', 'S', 'WILDWEST','MALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Szeryf', 'L', 'WILDWEST','MALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Cowboy', 'M', 'WILDWEST','MALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Piratka', 'S', 'PIRATES','FEMALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Kapitan Hak', 'M', 'PIRATES','MALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Korsarka', 'BIGMAMMA', 'PIRATES','FEMALE', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Scooby Doo', 'XL', 'ANIMALS','REST', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Tyranozaur Rex', 'M', 'ANIMALS','REST', null);
insert into costume (name, size, genre, sex, borrowed_till) values ('Myszka Miki', 'S', 'ANIMALS','REST', null);
commit;